batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      buildspec: build1.yml
      debug-session: true
      env:
        variables:
          BUILD_ID: build1
      ignore-failure: false
    - identifier: build2
      buildspec: build2.yml
      env:
        variables:
          BUILD_ID: build2
phases:
  build:
    commands:
      - echo Entered teh build phase ...
      - echo Build started on `date`
      - aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/997477333591/my-queue --message-body "Hello, world"
