version: 0.2
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: true
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
    dynamic:
      env:
        compute-type:
          - BUILD_GENERAL1_MEDIUM
        image:
          - public.ecr.aws/lambda/nodejs:14.2023.05.29.17
        variables:
          WORKERS:
            - 1
            - 2
phases:
 pre_build:
    commands:
      - ls